kind: Service
apiVersion: v1
metadata:
  name: rabbitmq-management
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
spec:
  type: LoadBalancer
  selector:
    app: rabbitmq
  ports:
  - name: management-console
    port: 15672
